/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matrixjavagui.hiya;

import java.awt.Dimension;
import java.awt.TextField;

/**
 *
 * @author Touyashi
 */
public class Operation extends javax.swing.JFrame {
    int m1 = 0, m2 = 0, mh = 0;
    TextField matrix1[], matrix2[], matrixh[];

    /**
     * Creates new form Transpose
     */
    public Operation() {
        initComponents();
        choiceOperation.add("Penjumlahan");
        choiceOperation.add("Pengurangan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRow = new java.awt.Label();
        labelColumn = new java.awt.Label();
        textFieldRow = new java.awt.TextField();
        textFieldColumn = new java.awt.TextField();
        buttonShowColumn = new java.awt.Button();
        buttonCount = new java.awt.Button();
        buttonBack = new java.awt.Button();
        scrollPaneContent = new java.awt.ScrollPane();
        panelContent = new java.awt.Panel();
        choiceOperation = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operasi Hitung");

        labelRow.setText("Baris");

        labelColumn.setText("Kolom");

        textFieldRow.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldRow.setText("0");

        textFieldColumn.setText("0");

        buttonShowColumn.setLabel("Tampilkan Kolom");
        buttonShowColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowColumnActionPerformed(evt);
            }
        });

        buttonCount.setEnabled(false);
        buttonCount.setLabel("Hitung");
        buttonCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCountActionPerformed(evt);
            }
        });

        buttonBack.setLabel("Kembali");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        panelContent.setPreferredSize(new java.awt.Dimension(1000, 500));

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        scrollPaneContent.add(panelContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(choiceOperation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldRow, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonShowColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonShowColumn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneContent, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        matrix.Main main = new matrix.Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonShowColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowColumnActionPerformed
        // TODO add your handling code here:
        int Kolom = Integer.parseInt(textFieldColumn.getText());
        int Baris = Integer.parseInt(textFieldRow.getText());
        int Dimension = Kolom*Baris;
        
        if (Dimension > 0) {
            if (m1 > 0 && m2 > 0) {
                for (int i = 0; i < matrix1.length; i++) {
                    matrix1[i].setVisible(false);
                }
                for (int i = 0; i < matrix2.length; i++) {
                    matrix2[i].setVisible(false);
                }
            }

            matrix1 = new TextField[Dimension];
            matrix2 = new TextField[Dimension];
            int num = 0;
            int x1 = 10, x2 = 10;
            int y1 = 10, y2 = (40*Baris)+30;
            for (int b = 1; b <= Baris; b++) {
                for (int k = 1; k <= Kolom; k++) {
                    matrix1[num] = new TextField();
                    matrix1[num].setBounds(x1, y1, 35, 35);
                    matrix1[num].setText("0");
                    panelContent.add(matrix1[num]);

                    matrix2[num] = new TextField();
                    matrix2[num].setBounds(x2, y2, 35, 35);
                    matrix2[num].setText("0");
                    panelContent.add(matrix2[num]);

                    num++;
                    x1 += 40;
                    x2 += 40;
                }
                x1 = 10;
                x2 = 10;
                y1 += 40;
                y2 += 40;
            }
            m1 = 1;
            m2 = 1;
            buttonCount.setEnabled(true);
        } else {
            buttonCount.setEnabled(false);
        }
    }//GEN-LAST:event_buttonShowColumnActionPerformed

    private void buttonCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCountActionPerformed
        // TODO add your handling code here:
        int Kolom = Integer.parseInt(textFieldColumn.getText());
        int Baris = Integer.parseInt(textFieldRow.getText());
        int Dimension = Kolom*Baris;
        String operasi = choiceOperation.getSelectedItem().toString();
        
        if (mh > 0) {
            for (int i = 0; i < matrixh.length; i++) {
                matrixh[i].setVisible(false);
            }
        }
        
        matrixh = new TextField[Dimension];
        int num = 0;
        int x = (Kolom*40)+50;
        int y = 10;
        for (int b = 1; b <= Baris; b++) {
            for (int k = 1; k <= Kolom; k++) {
                int matrix1val = Integer.parseInt(matrix1[num].getText());
                int matrix2val = Integer.parseInt(matrix2[num].getText());
                int Hasil;
                if (operasi == "Penjumlahan") {
                    Hasil = matrix1val + matrix2val;
                } else {
                    Hasil = matrix1val - matrix2val;
                }

                matrixh[num] = new TextField();
                matrixh[num].setBounds(x, y, 35, 35);
                matrixh[num].setText(""+Hasil);
                panelContent.add(matrixh[num]);

                x += 40;
                num++;
            }
            x = (Kolom*40)+50;
            y += 40;
            
            
        }
        mh=1;
    }//GEN-LAST:event_buttonCountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonBack;
    private java.awt.Button buttonCount;
    private java.awt.Button buttonShowColumn;
    private java.awt.Choice choiceOperation;
    private java.awt.Label labelColumn;
    private java.awt.Label labelRow;
    private java.awt.Panel panelContent;
    private java.awt.ScrollPane scrollPaneContent;
    private java.awt.TextField textFieldColumn;
    private java.awt.TextField textFieldRow;
    // End of variables declaration//GEN-END:variables
}
